# Generated by Django 2.1.5 on 2019-02-08 22:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("char_field", models.CharField(max_length=12)),
                ("int_field", models.PositiveIntegerField(default=2)),
                ("decimal_field", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        )
    ]
