# Generated by Django 2.1.5 on 2019-02-08 22:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("demo_app", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="dummymodel", name="int_field"),
        migrations.AddField(
            model_name="dummymodel",
            name="new_char_field",
            field=models.CharField(blank=True, max_length=200, verbose_name="An another CharField"),
        ),
        migrations.AlterField(
            model_name="dummymodel",
            name="char_field",
            field=models.CharField(blank=True, max_length=200, verbose_name="CharField FieldBusted !"),
        ),
        migrations.AlterField(
            model_name="dummymodel",
            name="decimal_field",
            field=models.DecimalField(
                decimal_places=3, default=2.3, max_digits=14, verbose_name="Decimal Field FieldBustier"
            ),
        ),
    ]
