name: GitHub Actions Django-Fieldbustier
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: fieldbustier
          POSTGRES_PASSWORD: fieldbustier
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
#          django-version: ["django~=1.11", "django~=2.0", "django~=2.1", "django~=2.2" ]
          tox-env: ["lints", "django111", "django20", "django21", "django22"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
#        pip install ${{ matrix.django-version }}
#    - name: Run Demo_app Tests
#      run: python demo_tests/manage.py test demo_app --noinput
#    - name: Run Fieldbustier Tests
#      run: python demo_tests/manage.py test fieldbustier_tests --settings=demo_tests.settings_with_fieldbustier --noinput
    - name: Run tox
      run: tox -e ${{ matrix.tox-env }}
